require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LecturesController, type: :controller do

  before do
      request.env['omniauth.auth'] = OmniAuth.config.mock_auth[:facebook]
  end
  # This should return the minimal set of attributes required to create a valid
  # Lecture. As you add validations to Lecture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {
    id: '10',
    title: "Palestra do momento",
    theme: "huehue",
    address: "asdsada",
    description: "Descrição da palestra 1",
    latitude: '29.55889609999999',
    longitude: '-98.  3799995',
    price: "0.0",
    duration: "1",
    date: "2015-11-19 21:40:50",
    created_at: "2015-11-19 21:40:50",
    updated_at: "2015-11-19 21:40:50",
    speaker_id: "1"
  }}

  let(:user_valid_attributes) {{
    id: '1',
    provider: "facebook",
    uid: "883752575071021",
    name: "alebr28@hotmail.com",
    image: "http://graph.facebook.com/883752575071021/picture",
    token: "CAACuAWK5tJABAAuHm5Hv6ZCtQHUn4s1VGq6NyHe6pcaY9PRDH...",
    expires_at: "2016-01-21 21:21:17",
    review_id: '1',
    created_at: "2015-11-22 22:53:31",
    updated_at: "2015-11-22 22:53:31",
    email: "alebr28@hotmail.com"

  }}

  let(:invalid_attributes) {{
    id: '1',
    title: "Palestra do momento",
    theme: "huehue",
    address: "asdsada",
    description: "Descrição da palestra 1",
    latitude: '29.55889609999999',
    longitude: '-98.3799995',
    price: "asdasda",
    duration: "asdasd",
    date: "2015-11-19 21:40:50",
    created_at: "2015-11-19 21:40:50",
    updated_at: "2015-11-19 21:40:50",
    speaker_id: "1"
  }}

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LecturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    before do
      Lecture.delete_all
    end
    it "assigns all lectures as @lectures" do
      lecture = Lecture.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:lectures)).to eq([lecture])
    end
  end

  describe "GET #show" do
    it "assigns the requested lecture as @lecture" do
      user = User.create! user_valid_attributes
      lecture = Lecture.create! valid_attributes
      get :show, {:id => lecture.to_param}, valid_session
      expect(assigns(:lecture)).to eq(lecture)
    end
  end

  describe "GET #new" do
    it "assigns a new lecture as @lecture" do
      get :new, {}, valid_session
      expect(assigns(:lecture)).to be_a_new(Lecture)
    end
  end

  describe "GET #edit" do
    it "assigns the requested lecture as @lecture" do
      lecture = Lecture.create! valid_attributes
      get :edit, {:id => lecture.to_param}, valid_session
      expect(assigns(:lecture)).to eq(lecture)
    end
  end

  describe "POST #create" do
    before do
     post :create, provider: :facebook
   end
    context "with valid params" do
      it "creates a new Lecture" do
        expect {
          post :create, valid_attributes , valid_session
        }.to change(Lecture, :count).by(1)
      end

      it "assigns a newly created lecture as @lecture" do
        post :create, {:lecture => {}}, valid_session
        expect(assigns(:lecture)).to be_a(Lecture)
        expect(assigns(:lecture)).to be_persisted
      end

      it "redirects to the created lecture" do
        post :create, {:lecture => valid_attributes}, valid_session
        expect(response).to redirect_to(Lecture.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved lecture as @lecture" do
        post :create, {:lecture => invalid_attributes}, valid_session
        expect(assigns(:lecture)).to be_a_new(Lecture)
      end

      it "re-renders the 'new' template" do
        post :create, {:lecture => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {{
        id: '1',
        title: "Palestra Atualizada",
        theme: "huehue",
        address: "asdsada",
        description: "Descrição da palestra 1",
        latitude: '29.55889609999999',
        longitude: '-98.3799995',
        price: "0.0",
        duration: "2",
        date: "2015-11-19 21:40:50",
        created_at: "2015-11-19 21:40:50",
        updated_at: "2015-11-19 21:40:50",
        speaker_id: "1"
      }}

      it "updates the requested lecture" do
        lecture = Lecture.create! valid_attributes
        put :update, {:id => lecture.to_param, :lecture => new_attributes}, valid_session
        lecture.reload
        expect(lecture.duration).to eq(2)
      end

      it "assigns the requested lecture as @lecture" do
        lecture = Lecture.create! valid_attributes
        put :update, {:id => lecture.to_param, :lecture => valid_attributes}, valid_session
        expect(assigns(:lecture)).to eq(lecture)
      end

      it "redirects to the lecture" do
        lecture = Lecture.create! valid_attributes
        put :update, {:id => lecture.to_param, :lecture => valid_attributes}, valid_session
        expect(response).to redirect_to(lecture)
      end
    end

    context "with invalid params" do
      it "assigns the lecture as @lecture" do
        lecture = Lecture.create! valid_attributes
        put :update, {:id => lecture.to_param, :lecture => invalid_attributes}, valid_session
        expect(assigns(:lecture)).to eq(lecture)
      end

      it "re-renders the 'edit' template" do
        lecture = Lecture.create! valid_attributes
        put :update, {:id => lecture.to_param, :lecture => invalid_attributes}, valid_session
        expect(response).to redirect_to(Lecture.last)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested lecture" do
      lecture = Lecture.create! valid_attributes
      expect {
        delete :destroy, {:id => lecture.to_param}, valid_session
      }.to change(Lecture, :count).by(-1)
    end

    it "redirects to the lectures list" do
      lecture = Lecture.create! valid_attributes
      delete :destroy, {:id => lecture.to_param}, valid_session
      expect(response).to redirect_to(lectures_url)
    end
  end

end
